applicationName: spring-cloud-k8s-demo
replicaCount: 1
minAvailable: 1

serviceAccount:
  name: spring-cloud-k8s-demo
  create: true

customResources:
  enabled: true
  resources:
    role: |
      kind: Role
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: config-map-readonly
      rules:
        - apiGroups: [""]
          resources: ["configmaps", "secrets"]
          verbs: ["get", "list", "watch"]
    role_binding: |
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: spring-cloud-k8s-demo-confimap-role-binding
      subjects:
        - kind: ServiceAccount
          name: spring-cloud-k8s-demo
          apiGroup: ""
      roleRef:
        kind: Role
        name: config-map-readonly
        apiGroup: ""


containerImage:
  repository: "ghcr.io/simonrowe/spring-cloud-k8s-demo"
  tag: v0.0.11
  pullPolicy: IfNotPresent


containerPorts:
  http:
    port: 8081


service:
  type: NodePort

  ports:
    app:
      port: 8081

    metrics:
      port: 8082


containerResources:
  requests:
    memory: 512Mi

  limits:
    memory: 1Gi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 9
  httpGet:
    path: /health/liveness
    port: 8082


readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 9

  httpGet:
    path: /health/readiness
    port: 8082


ingress:
  enabled: true
  path: "/"
  servicePort: "app"
  pathType: "Prefix"
  hosts:
    - spring-cloud-k8s-demo.com
